# Generated by Django 6.1 on 2026-08-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_featured_video_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(default='ტესტი', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='theme',
            field=models.CharField(default='ტესტი', max_length=30),
        ),
    ]
