# Generated by Django 6.1 on 2026-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_theme_video_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='theme',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
